# Generated by Django 5.2.10 on 2026-01-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_shoppingtrip_shoppingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingrequest',
            name='amount_to_pay_shopper',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shoppingrequest',
            name='estimated_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
