# Generated by Django 6.0.1 on 2026-02-09 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_shoppingrequest_amount_to_pay_shopper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAdminFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fee_payments', to='marketplace.business')),
            ],
        ),
    ]
