# Generated by Django 6.0.1 on 2026-02-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_businessadminfeepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map location', max_digits=9, null=True),
        ),
    ]
