# Generated by Django 6.0.1 on 2026-02-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_business_latitude_business_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessadminfeepayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='businessadminfeepayment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_payments/'),
        ),
    ]
