# Generated by Django 6.0.1 on 2026-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_businessadminfeepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBankingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=10)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('current', 'Current')], default='current', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Optional reference for payments', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Banking Details',
                'verbose_name_plural': 'Admin Banking Details',
            },
        ),
    ]
